### ISSUE TITLE
Requests to MAX devices doesnt work

### ISSUE THREAD

**Issue by maufc** [PLCHome/growatt#12]
Hi.
Requests to MAX devices are not working anymore. 
It seems like the address had change.
Does anybody found the solution?
Thanks.
Regards!

**Comment by PLCHome** [comment]
Check the token please
Thanks.

**Comment by PLCHome** [comment]
Answer the questions:

**Describe your inverter**

Typ, modell, ...
The enviroment (panels, accu etc.)
The modell of the logger

**Describe the bug**  
A clear and concise description of what the bug is.

**To Reproduce**  
Steps to reproduce the behavior:

1. Go to '...'
2. Click on '...'
3. Scroll down to '....'
4. See error

**Expected behavior**  
A clear and concise description of what you expected to happen.

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**

- Adapter version: <adapter-version>
- JS-Controller version: <js-controller-version> 
- Node version: <node-version> 
- Operating system: <os-name>

**Additional context**  
Add any other context about the problem here.
