### ISSUE TITLE
Add Support for server-us.growatt.com

### ISSUE THREAD

**Issue by mumblebaj** [PLCHome/growatt#18]
Is it possible to add support for server-us.growatt.com? An option as part of the options to select the region to use perhaps? I have users of my module who are only able to access [server-us.growatt.com](https://server-us.growatt.com) and cannot access [server.growatt.com](https://server.growatt.com).  Would this be possible?  Not sure if there are other regions.

```
const options = {
  plantData: true, weather: false, totalData: true, statusData: true, deviceData: true,
  deviceType: false, historyLast: true, historyAll: false, usServer: true
}
```

Thanks in advance
Bernard

**Comment by PLCHome** [comment]
It is implemented in the constructor.
```
 const growatt = new api({server: 'https://server-us.growatt.com/'})
```

The same for  C&I Plants. 


## Constructor

Please note that you have to create an instance since version 0.2.0.

| Parameter | Type   | Default   | Description             |
| --------- | ------ | --------- | ----------------------- |
| config    | Object | See below | Controls the processing |

The constructor has a config object as parameter. This is optional.

### Config

| config           | Type     | Default                      | Description                                                                                                                   |
| ---------------- | -------- | ---------------------------- | ----------------------------------------------------------------------------------------------------------------------------- |
| server           | String   | 'https://server.growatt.com' | The Growatt server                                                                                                            |
| indexCandI       | Boolean  | false                        | Set to true if your Growatt page Plant is a C&I Plant page with indexbC or plantDo in the Path from the Growatt webinterface. |
| timeout          | Integer  | 5000                         | Session timeout in ms.                                                                                                        |
| headers          | Object   | {}                           | custom header like {'X-Custom-Header': 'foobar'}.                                                                             |
| lifeSignCallback | function | undefined                    | Called before each Axios call.                                                                                                |

```
const api = require('growatt')
const growatt = new api()
```
