### ISSUE TITLE
Help in understanding `weather` option

### ISSUE THREAD

**Issue by Greenie10** [PLCHome/growatt#9]
Hi - thanks for creating this repo. I have questions about the `weather` option. 

On the Growatt.com website dashboard, the weather information changes regularly. However in your app, when `historyAll: true` there is no weather info at each history data point, only at the 'top' level (and that is output out-of-date, eg, it is 2022-07-22 17:53 now when I am typing this, however, the timestamp for the weather info, when I run it right now, is 2022-07-21 15:45, roughly a day and 2 hours behind.  Is this a limitation of the growatt API, or is there a way to get the weather info for each data point?

I am interested in doing this because I would like to compare the cloud coverage at each moment with the solar collection.

Thank you
Laura

**Comment by PLCHome** [comment]
Hello Laura, 
Growatt does not provide historical weather data. Only the current weather data can be retrieved. Since the API reads the website, the data is the same. The historical data was introduced because Growatt puts out some additional inverter data there that you won't find anywhere else on the website.
I can't add any data either. The API sends the same request as the website and gets a JSON back. This is then returned.
You can poll and save the data when the timestamp for the update changes.
